#!/bin/bash

echo "🆓 Deploying Person Detection App for FREE!"
echo "=========================================="

echo ""
echo "🚂 Option 1: Railway (RECOMMENDED)"
echo "1. Go to https://railway.app"
echo "2. Sign up with GitHub"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select your repository"
echo "5. Railway auto-detects everything!"
echo "6. Your app is live in 2 minutes!"
echo ""

echo "🎨 Option 2: Render"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Configure:"
echo "   - Name: person-detection-app"
echo "   - Environment: Node"
echo "   - Build Command: npm install && cd client && npm install && npm run build"
echo "   - Start Command: node server.js"
echo "   - Plan: Free"
echo "6. Click 'Create Web Service'"
echo ""

echo "⚡ Option 3: Vercel (CLI)"
echo "npm i -g vercel"
echo "vercel"
echo ""

echo "🌐 Option 4: Netlify"
echo "1. Go to https://netlify.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New site from Git'"
echo "4. Select your repository"
echo "5. Configure build settings"
echo ""

echo "🎯 RECOMMENDED: Railway"
echo "✅ Easiest setup"
echo "✅ Perfect for Python + Node.js"
echo "✅ No configuration needed"
echo "✅ Free custom domain"
echo "✅ 500 hours/month free"
echo ""

echo "Ready to deploy? Choose Railway for the best experience!"
echo "🌐 https://railway.app"
