[build]
builder = "nixpacks"
dockerfilePath = ""

[deploy]
startCommand = "bash railway-start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production", PORT = "5000" }