services:
  - type: web
    name: person-detection-app
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
