[phases.setup]
nixPkgs = ["python311", "nodejs_20", "python311Packages.pip"]

[phases.install]
cmds = [
  "python3 --version",
  "pip3 install --upgrade pip",
  "pip3 install -r requirements.txt",
  "npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]